apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: josefs-secret-rs
  labels:
    app: josefs-secret
spec:
  replicas: 6
  selector:
    matchLabels:
      app: josefs-secret
  template:
    metadata:
      labels:
        app: josefs-secret
    spec:
      containers:
      - name: josefs-secret-app
        image: matte250/josefs-secret:latest
